export const PATH = {
	ROOT: '/',
	SIGNIN: '/signin',
	SIGNUP: '/signup',
	SCHEDULE: '/schedule',
	CHAT: '/chat',
	FEED: '/feed',
	ENTRY: '/entry',
	REDIRECT: '/redirect',
	INVITE: '/invite',
	DOCUMENT: '/document',
	PRESENTATION: '/presentation',
	SETTING: '/setting',
	MYPAGE: '/mypage',
} as const;
