name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ap-northeast-2
      S3_BUCKET: colla.so

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Display node version
        run: node --version

      - name: .env.production setting
        run: |
          echo "VITE_KAKAO_REST_API_KEY=${{ secrets.VITE_KAKAO_REST_API_KEY }}" >> .env.production
          echo "VITE_KAKAO_REDIRECT_URL=${{ secrets.VITE_KAKAO_REDIRECT_URL }}" >> .env.production

          echo "VITE_GOOGLE_CLIENT_ID=${{ secrets.VITE_GOOGLE_CLIENT_ID }}" >> .env.production
          echo "VITE_GOOGLE_REDIRECT_URL=${{ secrets.VITE_GOOGLE_REDIRECT_URL }}" >> .env.production

          echo "VITE_NAVER_CLIENT_ID=${{ secrets.VITE_NAVER_CLIENT_ID }}" >> .env.production
          echo "VITE_NAVER_REDIRECT_URL=${{ secrets.VITE_NAVER_REDIRECT_URL }}" >> .env.production
          echo "VITE_NAVER_STATE=${{ secrets.VITE_NAVER_STATE }}" >> .env.production

          echo "VITE_NODE_ENV=${{ secrets.VITE_NODE_ENV }}" >> .env.production
          echo "VITE_BASE_URL=${{ secrets.VITE_BASE_URL }}" >> .env.production
          echo "VITE_SOCKET_URL=${{ secrets.VITE_SOCKET_URL }}" >> .env.production
          echo "VITE_IMAGE_SOURCE_HOSTNAME=${{ secrets.VITE_IMAGE_SOURCE_HOSTNAME }}" >> .env.production
          echo "VITE_IMAGE_TRANSFORM_BASE_URL=${{ secrets.VITE_IMAGE_TRANSFORM_BASE_URL }}" >> .env.production

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Exclude MSW worker from production
        run: rm --force dist/mockServiceWorker.js

      - name: Validate production
        run: |
          test -f dist/index.html
          test -d dist/assets
          test ! -f dist/mockServiceWorker.js

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.2.3
        with:
          aws-access-key-id: ${{ secrets.AWS_IAM_MANAGER_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_IAM_MANAGER_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload assets
        run: |
          aws s3 sync dist/assets "s3://${S3_BUCKET}/assets" \
            --cache-control "public,max-age=31536000,immutable"

      - name: Upload static files
        run: |
          aws s3 sync dist "s3://${S3_BUCKET}" \
            --exclude "assets/*" \
            --exclude "index.html" \
            --cache-control "no-cache,must-revalidate" \
            --delete

      - name: Upload index
        run: |
          aws s3 cp dist/index.html "s3://${S3_BUCKET}/index.html" \
            --cache-control "no-cache,must-revalidate" \
            --content-type "text/html; charset=utf-8"
